### ISSUE TITLE
Styled-Components documentation missing

### ISSUE THREAD

**Issue by bethwickerson** [pixelass/react-stickyroll#307]
Trying to get to this section in the documentation, but the page is missing
https://stickyroll.github.io/react-stickyroll/doc/guide/styled-components/Readme.html

I am hoping to figure out how to use {progress} with css to pull my headline in from the left like in the demo page.

**Comment by pixelass** [comment]
Thank you for reporting this issue. I already answered in our support chat but I'll try to add the missing documentation in the next few days. More info can be found in the chat.

**Comment by pixelass** [comment]
Here's the `progressable` implementation used by the headline you mentioned
https://github.com/stickyroll/react-stickyroll/blob/master/src/cover/src/progressable.ts

Here's how I use it: 
https://github.com/stickyroll/react-stickyroll/blob/master/src/cover/src/device-support.tsx#L270

**Comment by pixelass** [comment]
Sadly I currently can't update the guide due to https://github.com/patternplate/patternplate/issues/334

I would have to rewrite the entire guide which is too much work right now.

I have a local branch `chore/v2` which already fixes this and uses next.js for the demo. I might switch to storyboard for the examples.

Help is appreciated. Further info will be given when I find more time.

Please ask questions here or in the live-support chat and I will do my best to give support.

I am very sorry for this inconvenience
